apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: fp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835-sa
      containers:
      - name: flask-app
        image: 537380924761.dkr.ecr.us-east-1.amazonaws.com/clo835-flask-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKGROUND_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: background-config
              key: BACKGROUND_IMAGE_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials-secret
              key: aws_session_token
      imagePullSecrets:
      - name: ecr-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: fp
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 8080
