name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t clo835-flask-app .
          docker tag clo835-flask-app:latest 537380924761.dkr.ecr.us-east-1.amazonaws.com/clo835-flask-app:latest

      - name: Push Docker image to ECR
        run: |
          docker push 537380924761.dkr.ecr.us-east-1.amazonaws.com/clo835-flask-app:latest

